language: ruby

rvm:
- 2.5.1

script:
- bundle exec rails db:migrate 
- bundle exec rspec -fd spec

deploy:
  provider: heroku
  api_key:
    secure: b0fda0fa-a20a-4901-ab5a-200ba27b95c1
  strategy: git
  app: quiet-refuge-41570
  run: "rails db:migrate"

env:
  - BEERMAPPING_APIKEY="7a6180134816fccd0b81cc16bf0659ff"
  - APIXU_APIKEY="ecf722245d2b4c2fa80193833181310"
